#!/usr/bin/env bash

# For custom themes from default/themes, need to run this script manually

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
YTM_DIR="$XDG_CONFIG_HOME/YouTube Music"
TEMPLATE="$YTM_DIR/ytmusic.css"
OUTPUT="$YTM_DIR/style.css"
SHELL_CONFIG="$XDG_CONFIG_HOME/illogical-impulse/config.json"

# Get current wallpaper and mode from quickshell config
if [ -f "$SHELL_CONFIG" ]; then
    WALLPAPER=$(jq -r '.background.wallpaperPath' "$SHELL_CONFIG")
    MODE=$(gsettings get org.gnome.desktop.interface color-scheme 2>/dev/null | tr -d "'")
    if [[ "$MODE" == *"light"* ]]; then
        MODE_FLAG="light"
    else
        MODE_FLAG="dark"
    fi
    PALETTE_TYPE=$(jq -r '.appearance.palette.type' "$SHELL_CONFIG" 2>/dev/null || echo "scheme-tonal-spot")
    [ "$PALETTE_TYPE" == "auto" ] && PALETTE_TYPE="scheme-tonal-spot"
else
    # Fallbacks
    WALLPAPER="$1"
    MODE_FLAG="dark"
    PALETTE_TYPE="scheme-tonal-spot"
fi

if [ -z "$WALLPAPER" ] && [ -z "$1" ]; then
    echo -e "\e[31mError: No wallpaper found in config and no image provided as argument.\e[0m"
    echo "Usage: $0 [path_to_image]"
    exit 1
fi

[ -n "$1" ] && WALLPAPER="$1"

echo -e "\e[34mGenerating YouTube Music theme...\e[0m"
echo "Wallpaper: $WALLPAPER"
echo "Mode: $MODE_FLAG"
echo "Type: $PALETTE_TYPE"

CUSTOM_THEME="$HOME/.config/quickshell/ii/defaults/themes/$PALETTE_TYPE.json"
QUICKSHELL_COLORS="$HOME/.local/state/quickshell/user/generated/colors.json"

if [ -f "$CUSTOM_THEME" ]; then
    echo -e "\e[36mFound custom Quickshell theme ($PALETTE_TYPE). Reading directly...\e[0m"
    COLORS_JSON=$(cat "$CUSTOM_THEME")
elif [ -f "$QUICKSHELL_COLORS" ]; then
    echo -e "\e[36mFound colors generated by Matugen/Quickshell. Using existing colors...\e[0m"
    COLORS_JSON=$(cat "$QUICKSHELL_COLORS")
else
    # Fallback to generating colors natively with Matugen
    echo -e "\e[36mFalling back to Matugen CLI for color generation...\e[0m"
    COLORS_JSON=$(matugen image "$WALLPAPER" --mode "$MODE_FLAG" --type "$PALETTE_TYPE" -j hex 2>/dev/null)
fi

if [ -z "$COLORS_JSON" ]; then
    echo -e "\e[31mError: Failed to fetch generated colors.\e[0m"
    exit 1
fi

# Apply the generated colors to ytmusic.css using Python regex replacer
python3 -c "
import sys, json, re

try:
    data = json.loads(sys.argv[1])
    # Handle both Matugen's nested JSON and Quickshell's flat JSON scheme
    if 'colors' in data and sys.argv[4] in data['colors']:
        colors = data['colors'][sys.argv[4]]
    else:
        colors = data
except Exception as e:
    print('Failed to parse JSON color output:', e)
    sys.exit(1)

template_path = sys.argv[2]
output_path = sys.argv[3]

with open(template_path, 'r') as f:
    css = f.read()

def replacer(match):
    color_name = match.group(1)
    return colors.get(color_name, match.group(0))

new_css = re.sub(r'\{\s*\{\s*colors\.([a-zA-Z0-9_]+)\.default\.hex\s*\}\s*\}', replacer, css)

with open(output_path, 'w') as f:
    f.write(new_css)
" "$COLORS_JSON" "$TEMPLATE" "$OUTPUT" "$MODE_FLAG"

echo -e "\n\e[32mDone! style.css has been updated in $YTM_DIR\e[0m"
echo -e "\e[33m[IMPORTANT] Manual application might be required:\e[0m"
echo -e "If the theme is not active, open YouTube Music Desktop settings,"
echo -e "go to 'Visual Tweaks', and manually import the following file:"
echo -e "\e[36m$YTM_DIR/style.css\e[0m"
